name: CI

on:
  push:
  pull_request:

jobs:
  test:
    runs-on: ubuntu-latest
    env:
      REQRES_API_KEY: ${{ secrets.REQRES_API_KEY }}
      SLACK_WEBHOOK_URL: ${{ secrets.SLACK_WEBHOOK_URL }}
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: "20"
          cache: "npm"

      - name: Install dependencies
        run: npm ci

      - name: Install Playwright Browsers
        run: npx playwright install --with-deps

      - name: Lint & Type-Check
        run: |
          npm run lint 
          npm run format:check

      - name: Run UI Tests
        run: npx playwright test tests/ui --reporter=html

      - name: Run API Tests
        run: npx playwright test tests/api --reporter=html

      - name: Upload HTML Reports
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: playwright-reports
          path: playwright-report
          if-no-files-found: ignore
          retention-days: 7

      - name: Upload Traces
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: traces
          path: |
            test-results/**/*.zip
            test-results/**/trace.zip
          if-no-files-found: ignore
          retention-days: 7
      - name: Notify to Slack
        if: always()
        run: |
          STATUS=${{ job.status }}
          curl -X POST \
             -H 'Content-type: application/json' \
             --data "{\"text\":\":robot_face: CI finished with *$STATUS* on *${{ github.repository }}* (run ${{ github.run_id }})\"}" \
             "${{ secrets.SLACK_WEBHOOK_URL }}"
      - name: Notify to whatsapp
        if: always()
        run: |
          if [ -z "${{ secrets.TWILIO_SID }}" ] || [ -z "${{ secrets.TWILIO_KEY_SID }}" ] || [ -z "${{ secrets.TWILIO_KEY_SECRET }}" ] || [ -z "${{ secrets.TWILIO_WHATSAPP_FROM }}" ] || [ -z "${{ secrets.TWILIO_TO }}" ]; then
            echo "Twilio credentials are not set. Skipping WhatsApp notification."
            exit 0
          fi
          STATUS=${{ job.status }}
          MESSAGE="ðŸ¤– CI finished with status: *$STATUS* on *${{ github.repository }}* (run ${{ github.run_id }})"



          curl -X POST "https://api.twilio.com/2010-04-01/Accounts/${{ secrets.TWILIO_SID }}/Messages.json" \
          --data-urlencode "From=${{ secrets.TWILIO_WHATSAPP_FROM }}" \
          --data-urlencode "To=${{ secrets.TWILIO_TO }}" \
          --data-urlencode "Body=$MESSAGE" \
          -u "${{ secrets.TWILIO_KEY_SID }}:${{ secrets.TWILIO_KEY_SECRET }}"
      - name: notify to telegram
        if: always()
        run: |
          if [ -z "${{ secrets.TELEGRAM_BOT_TOKEN }}" ] || [ -z "${{ secrets.TELEGRAM_CHAT_ID }}" ]; then
           echo "Telegram secrets are not set. Skipping Telegram notification  ."
           exit 0
          fi
          STATUS=${{ job.status }} 
          REPO=${{ github.repository }}
          RUN=${{ github.run_id }}
          TEXT="ðŸ¤– CI finished with status: *$STATUS* on *$REPO* (run $RUN)"


          curl -X POST "https://api.telegram.org/bot${{ secrets.TELEGRAM_BOT_TOKEN }}/sendMessage" \
          -d chat_id="${{ secrets.TELEGRAM_CHAT_ID }}" \
          -d parse_mode="Markdown" \
          --data-urlencode "text=$TEXT"
